/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113224-gde9bc4f205-20240105"
#endif /* AVUTIL_FFVERSION_H */
